export const SET_LOGIN = "SET_LOGIN";
export const SET_SELECTED_LOGIN_OPTION = "SET_SELECTED_LOGIN_OPTION";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_FORM_PAGE = "SET_FORM_PAGE";
export const UPDATE_FORM_FIELDS = "UPDATE_FORM_FIELDS";
export const LOGOUT = "LOGOUT";
export const SET_ALL_LOCAL_DATA = "SET_ALL_LOCAL_DATA";
